name             'lwrp_logstash'
maintainer       'Simon Johansson'
maintainer_email 'simon@simonjohansson.com'
license          ''
description      'Installs/Configures lwrp_logstash'
long_description 'Installs/Configures lwrp_logstash'
version          '0.2.0'

depends 'yum', '~> 3.0.6'
depends 'apt', '~> 2.3.10'
